(ns is.simm.ops.proposals-fork-test
  "Per-fork accept/dismiss inside ONE proposal.

   The case this pins: several agents contribute a fork each to one ForkSet and
   the reviewer refuses exactly one of them. Before per-fork resolution the
   reviewer's only moves were all-or-nothing, so one unacceptable contribution
   cost the others their landing.

   What makes it safe is that a fork is an independent branch on its own scope:
   accepting three and dismissing one filters the merge loop, and never asks the
   3-way merge for part of a branch. So the assertions are about TRUNKS — the
   dismissed fork's page must not exist on its own trunk, and the accepted one's
   must — rather than about the proposal row, which could agree while the stores
   disagreed."
  (:require [clojure.test :refer [deftest is testing]]
            [datahike.api :as d]
            [is.simm.model.store :as store]
            [is.simm.model.system-db :as sdb]
            [is.simm.ops.proposals :as props]
            [is.simm.runtimes.branching :as branching]
            [is.simm.runtimes.context :as ctx]))

(defn- fresh-kb
  "A registered, branchable KB. `:commit-graph?` is what branch ancestry is read
   from and `:crypto-hash?` requires it — without both, `merge-kb!` has no graph
   to merge over and the test would pass vacuously."
  []
  (let [scope (random-uuid)
        cfg {:store {:backend :memory :id scope}
             :keep-history? true
             :crypto-hash? true
             :commit-graph? true
             :schema-flexibility :write}]
    (d/create-database cfg)
    (let [conn (d/connect cfg)]
      ;; `install!` rather than the schema alone: `:S.Page/title` is generated by
      ;; the seed's morphism->attribute machinery, so a bare schema transaction
      ;; leaves pages untransactable.
      (store/install! conn)
      (branching/register-system! conn scope)
      [scope conn])))

(defn- fresh-system-db
  "An in-memory stand-in for the shared system DB, carrying only simmis's
   extension schema. `sdb/init!` would connect to the project's real
   `.dvergr/system-db`."
  []
  (let [cfg {:store {:backend :memory :id (random-uuid)}
             :schema-flexibility :write :keep-history? false}]
    (d/create-database cfg)
    (doto (d/connect cfg) (d/transact sdb/schema))))

(defn- page-titled?
  "Does `scope`'s TRUNK carry a page with this title? Read through the registry
   rather than the connection the test opened, so a merge that landed somewhere
   other than the trunk this asserts on cannot pass."
  [scope title]
  (some? (d/q '[:find ?e . :in $ ?t :where [?e :S.Page/title ?t]]
              @(branching/get-kb-conn scope) title)))

(defn- fork-on
  "Branch `scope`, write one page on the branch, and return the fork map
   `file-proposal!` takes."
  [scope slug title]
  (let [base (branching/branch-head-id scope :db)
        {:keys [branch]} (branching/branch-kb! scope slug)]
    (d/transact (branching/get-kb-conn-on-branch scope branch)
                [{:entity/uuid (random-uuid) :S.Page/title title}])
    {:scope scope :branch branch :base-commit base :system-type :kb}))

(defn- fork-status [proposal-id scope]
  (->> (:proposal/forks (props/get-proposal proposal-id))
       (some #(when (= scope (:proposal.fork/scope %))
                (:proposal.fork/status %)))))

(deftest dismissed-fork-does-not-land-but-its-neighbour-does
  (ctx/with-server-context
    (let [sys-conn (fresh-system-db)]
      (with-redefs [sdb/get-conn (fn [] sys-conn)]
        (let [[keep-scope] (fresh-kb)
              [refuse-scope] (fresh-kb)
              keep-fork (fork-on keep-scope "handbook" "Refund window widened")
              refuse-fork (fork-on refuse-scope "notice" "Notice admitting liability")
              pid (props/file-proposal!
                   {:title "Customer refund programme"
                    :forks [keep-fork refuse-fork]})]
          (testing "one fork is refused; the ForkSet stays open for the rest"
            (let [r (props/dismiss-fork! pid refuse-scope (:branch refuse-fork)
                                         :note "admits legal liability")]
              (is (= :dismissed (:status r)))
              (is (nil? (:proposal r))
                  "a proposal with an open fork left must not resolve itself"))
            (is (= :open (:proposal/status (props/get-proposal pid))))
            (is (= :dismissed (fork-status pid refuse-scope)))
            (is (nil? (fork-status pid keep-scope)) "absent status means open"))

          (testing "the refused branch is gone, not merely flagged"
            (is (not (contains? (branching/list-kb-branches refuse-scope)
                                (:branch refuse-fork)))))

          (testing "accepting lands the survivors and skips the refusal"
            (is (= {:status :accepted} (props/accept-proposal! pid))
                "the dismissed fork must not reach the conflicts pre-check or
                 the merge loop — its branch no longer exists")
            (is (page-titled? keep-scope "Refund window widened")
                "the accepted fork landed on its own trunk")
            (is (not (page-titled? refuse-scope "Notice admitting liability"))
                "the refused fork must NOT be on its trunk")
            (is (= :accepted (fork-status pid keep-scope)))
            (is (= :dismissed (fork-status pid refuse-scope))
                "acceptance must not overwrite a recorded refusal"))

          (testing "the refusal keeps its reason"
            (let [f (->> (:proposal/forks (props/get-proposal pid))
                         (some #(when (= refuse-scope (:proposal.fork/scope %)) %)))]
              (is (= "admits legal liability" (:proposal/resolution-note f))))))))))

(deftest every-fork-dismissed-resolves-the-proposal-as-dismissed
  (ctx/with-server-context
    (let [sys-conn (fresh-system-db)]
      (with-redefs [sdb/get-conn (fn [] sys-conn)]
        (let [[scope] (fresh-kb)
              fork (fork-on scope "only" "The only contribution")
              pid (props/file-proposal! {:title "Single-fork proposal"
                                         :forks [fork]})
              r (props/dismiss-fork! pid scope (:branch fork))]
          (is (= :dismissed (:proposal r))
              "the last fork settling closes the ForkSet")
          (is (= :dismissed (:proposal/status (props/get-proposal pid)))
              "every contribution refused is a dismissal, not an acceptance of
               nothing")
          (is (not (page-titled? scope "The only contribution"))))))))

(deftest a-fork-can-be-landed-on-its-own
  (ctx/with-server-context
    (let [sys-conn (fresh-system-db)]
      (with-redefs [sdb/get-conn (fn [] sys-conn)]
        (let [[a-scope] (fresh-kb)
              [b-scope] (fresh-kb)
              a (fork-on a-scope "a" "Landed early")
              b (fork-on b-scope "b" "Still under review")
              pid (props/file-proposal! {:title "Two independent contributions"
                                         :forks [a b]})]
          (is (= {:status :accepted :proposal nil}
                 (props/accept-fork! pid a-scope (:branch a))))
          (is (page-titled? a-scope "Landed early"))
          (is (not (page-titled? b-scope "Still under review"))
              "the other fork is untouched by its neighbour landing")
          (is (= :open (:proposal/status (props/get-proposal pid))))
          (testing "resolving the last fork closes the ForkSet as accepted"
            (is (= :accepted (:proposal (props/accept-fork! pid b-scope (:branch b)))))
            (is (page-titled? b-scope "Still under review"))))))))

(deftest a-fork-resolves-once
  (ctx/with-server-context
    (let [sys-conn (fresh-system-db)]
      (with-redefs [sdb/get-conn (fn [] sys-conn)]
        (let [[scope] (fresh-kb)
              [other-scope] (fresh-kb)
              fork (fork-on scope "once" "Contribution")
              keep-open (fork-on other-scope "open" "Untouched")
              pid (props/file-proposal! {:title "Double resolution"
                                         :forks [fork keep-open]})]
          (props/dismiss-fork! pid scope (:branch fork))
          (is (thrown? clojure.lang.ExceptionInfo
                       (props/dismiss-fork! pid scope (:branch fork)))
              "a second decision on a settled fork would discard a branch that
               belongs to nobody")
          (is (thrown? clojure.lang.ExceptionInfo
                       (props/accept-fork! pid scope (:branch fork)))
              "and it must not be landable after being refused"))))))
