(ns is.simm.ops.semantic-diff-test
  "The `before` side of a deletion must be read at the MERGE BASE.

   Regression for a bug that hid for as long as it did because it failed
   quietly and only diverged under a race: `kb-db-at-commit` read the store off
   the `Connection` record rather than its deref, got nil for every KB and every
   commit, logged, and fell back to trunk. Trunk is the right ENTITY (one
   lineage, and datahike does not reuse eids) at the WRONG TIME — so it agrees
   with the base right up until trunk touches something the branch deleted."
  (:require [clojure.test :refer [deftest is testing]]
            [datahike.api :as d]
            [is.simm.model.store :as store]
            [is.simm.ops.semantic-diff :as sd]
            [is.simm.runtimes.branching :as branching]
            [is.simm.runtimes.context :as ctx]))

(defn- fresh-kb
  "A registered, branchable KB. `:commit-graph?` is what branch ancestry is read
   from and `:crypto-hash?` requires it — a store without both cannot answer
   `kb-db-at-commit` at all, so the test would pass vacuously."
  []
  (let [scope (random-uuid)
        cfg {:store {:backend :memory :id scope}
             :keep-history? true
             :crypto-hash? true
             :commit-graph? true
             :schema-flexibility :write}]
    (d/create-database cfg)
    (let [conn (d/connect cfg)]
      ;; `install!`, not `full-schema` alone — `:S.Page/title` is generated by
      ;; the seed's morphism->attribute machinery, so a bare schema transaction
      ;; leaves pages untransactable.
      (store/install! conn)
      (branching/register-system! conn scope)
      [scope conn])))

(defn- block-content-in
  "The `:before` text of every `:block/remove` op in a diff."
  [diff]
  (vec (for [p (:pages diff), o (:ops p) :when (= :block/remove (:op o))]
         (get-in o [:before :content]))))

(deftest kb-db-at-commit-resolves
  (testing "a commit id resolves to a db value — the store lives on the deref"
    (ctx/with-server-context
      (let [[scope conn] (fresh-kb)]
        (d/transact conn [{:entity/uuid (random-uuid) :S.Page/title "P"}])
        (let [head (branching/branch-head-id scope :db)]
          (is (some? head) "a KB with a commit graph has a head")
          (is (some? (branching/kb-db-at-commit scope head))
              "nil here means the caller silently reads trunk instead"))))))

(deftest deletion-before-is-read-at-the-base
  (testing "trunk editing a block the branch deleted does not rewrite `before`"
    (ctx/with-server-context
      (let [[scope conn] (fresh-kb)
            page-uuid (random-uuid)
            block-uuid (random-uuid)
            original "<p>the words the branch removed</p>"]
        (d/transact conn [{:entity/uuid page-uuid :S.Page/title "Handbook"}
                          {:entity/uuid block-uuid
                           :block/content original
                           ;; `:block/parent`, not a page ref — `anchor-page`
                           ;; walks parents upward until it finds a title.
                           :block/parent [:entity/uuid page-uuid]}])
        (let [base (branching/branch-head-id scope :db)
              {:keys [branch]} (branching/branch-kb! scope "delete-probe")
              bconn (branching/get-kb-conn-on-branch scope branch)]
          ;; the branch deletes the block …
          (d/transact bconn [[:db/retractEntity [:entity/uuid block-uuid]]])
          ;; … and trunk independently rewrites it. Both happen after the fork.
          (d/transact conn [{:entity/uuid block-uuid
                             :block/content "<p>what trunk says now</p>"}])
          (let [diff (sd/semantic-kb-diff scope branch :base-commit base)]
            (is (false? (boolean (:baseless? diff)))
                "the base resolved, so `before` came from it and not from trunk")
            (is (= [original] (block-content-in diff))
                "trunk's later text must not be presented as the deleted text")))))))
