(ns is.simm.model.store
  "ONE definition of what a simmis store contains.

   simmis has two creators of datahike stores — dvergr provisions a room's
   messages/KB/data stores, and `knowledge-bases` creates user-owned shareable
   KBs — but only one KIND of store. Both install the same simmis half here, so
   a KB can hold a book and a room store can hold wiki pages, and neither
   acquires an attribute the other lacks by accident.

   What is deliberately NOT here: the per-store wiring whose MECHANISM differs
   by creator — fulltext index declaration, yggdrasil registration, the
   branching-broadcast listener. Those stay at their call sites.

   Store CONFIG (the create-time-fixed flags) is the other half of the same
   idea and lives in `dvergr.system.rooms/store-cfg` and
   `knowledge-bases/kb-datahike-cfg`. The one create-time flag all three
   share, `:diff-buf-size`, is `dvergr.substrate.datahike/diff-buf-size` — the
   same measurement, already defined once for every dvergr store, and simmis
   had grown a second copy of it."
  (:require [is.simm.model.schema :as schema]
            [is.simm.model.seed :as seed]
            [is.simm.model.accounting :as accounting]
            [is.simm.model.katzen-projection :as katzen-proj]
            [katzen.schema.knowledge :as kb-schema]
            [datahike.api :as d]
            [taoensso.telemere :as log]))

;; =============================================================================
;; Late-added schema
;; =============================================================================

(def page-title-unique-schema
  "`:S.Page/title` as a uniqueness constraint — the katzen title:Entity->Identity
   binding contract. The DATABASE enforces one page per title, so lookup refs,
   the AVET fast path and strict `datahike.reference` resolution all work.

   `:db.unique/value`, not `/identity`: a second page claiming an existing title
   is an ERROR to surface, not an upsert that silently merges two pages.

   NEW STORES ONLY. datahike rejects altering `:db/unique` on an existing
   attribute (it would need a dup-check plus an AVET backfill, unimplemented),
   and `:S.Page/title` is generated by the seed's morphism->attribute machinery
   without it. So this must be transacted BEFORE the seed and only when the
   attribute is absent; a store that predates it keeps the app-level dedup and
   resolves titles via `datahike.reference`'s explicit non-unique path."
  [{:db/ident :S.Page/title
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one
    :db/unique :db.unique/value}])

(def kb-binding-opts
  "How katzen's `knowledge` schema binds onto category S — the binding functor
   of doc/kb-unification.md, in one place because every store applies the SAME
   binding and a second copy would drift.

   `:identify` — katzen's `Entity` IS the wiki page `S/Page`. No parallel
   `S/Entity` twin, and `title` projects onto the page title that already
   exists rather than duplicating it.

   `:storage-attrs` — `created-at`/`updated-at` are the UNIVERSAL entity
   timestamps every simmis entity already carries, not page-specific fields.
   Without this they would mint `:S.Page/created-at` alongside
   `:entity/created-at`: two attributes, one fact, and the page list reading
   the empty one."
  {:identify {:Entity "S/Page"}
   :storage-attrs {:Entity {:created-at :entity/created-at
                            :updated-at :entity/updated-at}}})

(defn project-kb-schema!
  "Project katzen's knowledge schema into this store's category S.

   Idempotent, and belongs on EVERY store: a KB store is where wiki pages
   actually live, so a KB whose S lacks `S/Page/summary` cannot render or query
   the property its own data carries. It ran only on the app store until now.

   Guarded — a projection failure degrades the categorical VIEW, it does not
   corrupt data, so it must not take down a store install."
  [conn]
  (try
    (katzen-proj/project-schema! conn kb-schema/schema kb-binding-opts)
    (catch Exception e
      (log/log! {:level :warn :id ::katzen-kb-project-failed
                 :msg "Could not project katzen KB schema into S"
                 :data {:error (.getMessage e)}})))
  conn)

(defn- ensure-late-schema!
  "Nothing. Kept as a named seam, with the reason it is empty.

   Every entry that lived here has moved into `schema/full-schema`, which
   `install!` re-transacts UNCONDITIONALLY on every store — so a migration
   function was never the mechanism that got attributes onto existing stores;
   `full-schema` already was. What the migration list actually did was decide
   which stores got the attribute at all: only those reached by this function,
   which is how three `:S.Message/*` attributes came to be missing from the app
   store while `columns.cljc` reads them in `:where` position against it.

   The rule this replaces: a NEW ATTRIBUTE GOES IN `full-schema`. If it cannot
   (a create-time-fixed flag like `:db/unique`), that is a store-config concern,
   not a migration — see `page-title-unique-schema`."
  [conn]
  conn)

;; =============================================================================
;; The installer
;; =============================================================================

(defonce ^:private installed
  ;; store-id -> installed this process. See `ensure!`.
  (atom #{}))

(defn install!
  "Install simmis's half into `conn`'s store: the category-S schema, page-title
   uniqueness, the seed entities, late-added attributes, and the kontor book.
   Idempotent — schema transactions upsert on `:db/ident`.

   ORDER MATTERS. The category-S schema must land before anything that writes
   category-S entities: `accounting/ensure-accounting-schema!` reflects the
   ledger types into S, so it would otherwise transact `:entity/uuid` against a
   store that does not define it yet.

   Accounting is installed on EVERY store, not just rooms. That is the point of
   one store kind — a KB someone created for a project can grow a book without
   being re-created. `ensure-accounting-schema!` is cheap on repeat: it installs
   the kernel schema only when absent and otherwise just re-registers the
   process-local writer governor.

   `at` INSTALLS THE STORE AT THE BEGINNING OF ITS NARRATIVE TIME. Without it
   every transaction here is stamped `(Date.)` while seeded content is
   back-dated to the months the scenario describes (demo.scenario/provenance),
   so the store's own vocabulary is younger than its content: at a cut between
   the two, `[?e :instance/of-role [:entity/name \"S/Page\"]]` throws `Nothing
   found for entity id [:entity/name \"S/Page\"]` rather than returning nothing
   (measured 2026-07-27), and the whole workspace is unreadable at exactly the
   reference the demo wants to stand on. Pass the earliest instant any content
   in this store will claim; omit it for real tenants, where the install IS
   happening now.

   NOT everything reachable from here can be stamped. `kontor.core/install-schema!`
   and katzen's projection own their transactions and take no `:tx-meta`, so
   accounting's ~8s of kernel writes still land at wall clock. That is survivable
   where the seed is not, because nothing on a client READ path resolves a
   `:kontor.*` entity through a lookup ref — the only lookup refs the client
   renders through are the category-S role entities, which this does stamp."
  ([conn] (install! conn nil))
  ([conn at]
   ;; One transaction, and the uniqueness only when `:S.Page/title` does not yet
   ;; exist — see `page-title-unique-schema`. Both must land BEFORE the seed,
   ;; whose morphism->attribute machinery would otherwise declare the attribute
   ;; without uniqueness and make it un-alterable.
   (d/transact conn
               (cond-> {:tx-data (cond-> (vec schema/full-schema)
                                   (not (d/q '[:find ?e . :where [?e :db/ident :S.Page/title]] @conn))
                                   (into page-title-unique-schema))}
                 at (assoc :tx-meta {:db/txInstant at})))
   (seed/ensure-seed-data! conn at)
   (ensure-late-schema! conn)
   (project-kb-schema! conn)
   (accounting/ensure-accounting-schema! conn)
   conn))

(defn ensure!
  "`install!`, once per store per process. The guard is in memory, not in the
   store: everything `install!` does is idempotent, but it is a few hundred
   transactions' worth of work and rooms are hydrated in bulk at boot.

   `at` is the store's narrative install instant — see `install!`. It only ever
   applies to the FIRST install in this process, which is the create path; a
   later connect re-installs (if the guard is cold) at wall clock, correctly, as
   that write really is happening then."
  ([conn store-id] (ensure! conn store-id nil))
  ([conn store-id at]
   (when store-id
     (locking installed
       (when-not (contains? @installed store-id)
         (install! conn at)
         (swap! installed conj store-id)
         (log/log! {:level :info :id ::installed
                    :msg "simmis schema installed on store"
                    :data {:store-id store-id :at at}}))))
   conn))
