(ns is.simm.agents.campaign-test
  "A room CAMPAIGN: several agents contributing to ONE proposal.

   The case this pins is the four-agent demo. Before campaigns, every agent held
   a private overlay keyed by [room agent], so four agents doing four halves of
   one change produced four proposals and the reviewer had no object saying
   `this is the joint change`. `open-campaign!` / `join-campaign!` put their
   forked writes into one room-level overlay, and whoever calls `file!` files all
   of it as a single ForkSet.

   The second assertion is the design decision: two agents writing the SAME
   database inside one campaign get a BRANCH EACH, filed as two forks, rather
   than sharing one. So the test reads the two branches and insists each carries
   only its own author's page — a shared branch would show both on each, and the
   per-fork accept/dismiss that landed in `ops.proposals` would have nothing to
   address."
  (:require [clojure.test :refer [deftest is testing]]
            [datahike.api :as d]
            [sci.core :as sci]
            [dvergr.tools.llm-call :as llm-call]
            [is.simm.agents.room-agents :as ra]
            [is.simm.model.store :as store]
            [is.simm.model.system-db :as sdb]
            [is.simm.ops.proposals :as props]
            [is.simm.runtimes.branching :as branching]
            [is.simm.runtimes.context :as ctx]))

(defn- fresh-kb
  "A registered, branchable KB carrying simmis's half. `:commit-graph?` is what
   branch ancestry is read from and `:crypto-hash?` requires it; `store/install!`
   rather than the schema alone because `:S.Page/title` is generated by the
   seed's morphism->attribute machinery, so `kb/ensure-page!` needs the seed."
  []
  (let [scope (random-uuid)
        cfg {:store {:backend :memory :id scope}
             :keep-history? true
             :crypto-hash? true
             :commit-graph? true
             :schema-flexibility :write}]
    (d/create-database cfg)
    (let [conn (d/connect cfg)]
      (store/install! conn)
      (branching/register-system! conn scope)
      [scope conn])))

(defn- fresh-system-db
  "An in-memory stand-in for the shared system DB, carrying only simmis's
   extension schema. `sdb/init!` would connect to the project's real
   `.dvergr/system-db`."
  []
  (let [cfg {:store {:backend :memory :id (random-uuid)}
             :schema-flexibility :write :keep-history? false}]
    (d/create-database cfg)
    (doto (d/connect cfg) (d/transact sdb/schema))))

(defn- agent-sandbox
  "One agent's SCI context, wired exactly as `join-agent!` wires it: `kb/*` over
   the room's KBs with an overlay resolved PER WRITE, and `proposal/*` bound to
   this (room, agent) pair. The two installers are private — this is the only
   place outside the agent boot path that needs them."
  [kb-conns room-uuid agent-uuid]
  (let [sci-ctx (sci/init {})
        overlay-fn #(#'ra/active-overlay room-uuid agent-uuid)]
    (#'ra/add-kb-write-ns! sci-ctx kb-conns overlay-fn agent-uuid)
    (#'ra/add-proposal-ns! sci-ctx room-uuid agent-uuid)
    sci-ctx))

(defn- page-on-branch?
  [scope branch title]
  (some? (d/q '[:find ?e . :in $ ?t :where [?e :S.Page/title ?t]]
              @(branching/get-kb-conn-on-branch scope branch) title)))

(defn- page-on-trunk? [scope title]
  (some? (d/q '[:find ?e . :in $ ?t :where [?e :S.Page/title ?t]]
              @(branching/get-kb-conn scope) title)))

(defn- stub-summary
  "`file!` asks a cheap LLM for the review-card prose. The test is about the
   ForkSet, not the prose, and a live call would make it a network test."
  [f]
  (with-redefs [llm-call/cheap-llm-call (fn [& _] {:text "stub summary"})]
    (f)))

(deftest campaign-files-one-proposal-with-a-fork-per-agent
  (ctx/with-server-context
    (let [sys-conn (fresh-system-db)]
      (with-redefs [sdb/get-conn (fn [] sys-conn)]
        (let [[scope] (fresh-kb)
              kb-conns [{:name "Handbook" :conn (branching/get-kb-conn scope)
                         :db-scope scope}]
              room (random-uuid)
              ada (random-uuid)
              bob (random-uuid)
              ada-ctx (agent-sandbox kb-conns room ada)
              bob-ctx (agent-sandbox kb-conns room bob)]

          (testing "one agent opens the campaign, the other joins it"
            (is (= "Q3 close" (:opened (sci/eval-string* ada-ctx
                                        "(proposal/open-campaign! \"Q3 close\")"))))
            (is (= "Q3 close" (:joined (sci/eval-string* bob-ctx
                                         "(proposal/join-campaign!)")))))

          (testing "each agent's writes fork the SAME KB onto its OWN branch"
            (sci/eval-string* ada-ctx "(kb/ensure-page! \"Handbook\" \"Ada's section\")")
            (sci/eval-string* bob-ctx "(kb/ensure-page! \"Handbook\" \"Bob's section\")")
            (let [forks (:forks (sci/eval-string* ada-ctx "(proposal/active)"))]
              (is (= 2 (count forks)) "one fork per contributor, on one scope")
              (is (= 2 (count (distinct (map :branch forks)))) "distinct branches")
              (is (= #{(str ada) (str bob)} (set (map :agent forks))))))

          (testing "nothing has reached trunk"
            (is (not (page-on-trunk? scope "Ada's section")))
            (is (not (page-on-trunk? scope "Bob's section"))))

          (testing "one member filing does NOT close the campaign for the rest"
            ;; The regression this guards: Ada calling file! used to record the
            ;; ForkSet and reset the shared overlay, dropping every other member.
            ;; Bob was still working, so his next write found no overlay and went
            ;; LIVE to trunk — silently, believing it was governed.
            (let [ada-done (stub-summary #(sci/eval-string* ada-ctx "(proposal/file! \"ada done\")"))]
              (is (false? (:filed ada-done)) "not filed while a member is outstanding")
              (is (= [(str bob)] (:waiting-for ada-done)))
              (is (zero? (count (props/list-proposals))) "no proposal exists yet"))

            (is (some? (sci/eval-string* bob-ctx "(proposal/active)"))
                "bob's campaign is still open")

            (testing "and bob's next write is still GOVERNED, not live"
              (sci/eval-string* bob-ctx "(kb/ensure-page! \"Handbook\" \"Bob's late section\")")
              (is (not (page-on-trunk? scope "Bob's late section")))))

          (testing "the LAST member to file files the whole campaign as ONE proposal"
            (let [filed (stub-summary #(sci/eval-string* bob-ctx "(proposal/file! \"joint\")"))
                  pid (parse-uuid (:proposal filed))
                  p (props/get-proposal pid)
                  forks (:proposal/forks p)]
              (is (true? (:campaign? filed)))
              (is (= 2 (:contributors filed)))
              (is (= 1 (count (props/list-proposals))) "ONE proposal, not one per agent")
              (is (= 2 (count forks)))
              (is (= #{scope} (set (map :proposal.fork/scope forks))))
              (is (every? :proposal.fork/base-commit forks) "each fork records its fork point")

              (testing "the branches stayed isolated — this is why they are separate forks"
                (let [[b1 b2] (map (comp keyword :proposal.fork/branch) forks)
                      ada-branch (if (page-on-branch? scope b1 "Ada's section") b1 b2)
                      bob-branch (if (= ada-branch b1) b2 b1)]
                  (is (page-on-branch? scope ada-branch "Ada's section"))
                  (is (not (page-on-branch? scope ada-branch "Bob's section")))
                  (is (page-on-branch? scope bob-branch "Bob's section"))
                  (is (not (page-on-branch? scope bob-branch "Ada's section")))))

              (testing "filing leaves every member a CLOSED marker, not nil"
                ;; nil would mean "you never proposed anything", which is exactly
                ;; the confusion that let post-filing writes go to trunk. The
                ;; marker is what makes the next governed write refusable.
                (doseq [[who ctx] [["ada" ada-ctx] ["bob" bob-ctx]]]
                  (let [a (sci/eval-string* ctx "(proposal/active)")]
                    (is (true? (:closed a)) (str who " sees the proposal as closed"))
                    (is (= "Q3 close" (:title a)))
                    (is (= (str pid) (:proposal a))))))

              (testing "a governed write after the filing is REFUSED, not trunked"
                (is (thrown-with-msg?
                     clojure.lang.ExceptionInfo #"no longer governed"
                     (sci/eval-string* ada-ctx "(kb/ensure-page! \"Handbook\" \"Too late\")")))
                (is (not (page-on-trunk? scope "Too late"))))

              (testing "release! is the deliberate way back to trunk"
                (sci/eval-string* ada-ctx "(proposal/release!)")
                (sci/eval-string* ada-ctx "(kb/ensure-page! \"Handbook\" \"Deliberate\")")
                (is (page-on-trunk? scope "Deliberate"))))))))))

(deftest private-proposals-are-unchanged-by-campaigns
  (testing "without a campaign each agent still files its own proposal"
    (ctx/with-server-context
      (let [sys-conn (fresh-system-db)]
        (with-redefs [sdb/get-conn (fn [] sys-conn)]
          (let [[scope] (fresh-kb)
                kb-conns [{:name "Handbook" :conn (branching/get-kb-conn scope)
                           :db-scope scope}]
                room (random-uuid)
                ada-ctx (agent-sandbox kb-conns room (random-uuid))
                bob-ctx (agent-sandbox kb-conns room (random-uuid))]
            (sci/eval-string* ada-ctx "(proposal/start! \"Ada's cleanup\")")
            (sci/eval-string* bob-ctx "(proposal/start! \"Bob's cleanup\")")
            (sci/eval-string* ada-ctx "(kb/ensure-page! \"Handbook\" \"A\")")
            (sci/eval-string* bob-ctx "(kb/ensure-page! \"Handbook\" \"B\")")
            (stub-summary #(do (sci/eval-string* ada-ctx "(proposal/file!)")
                               (sci/eval-string* bob-ctx "(proposal/file!)")))
            (is (= 2 (count (props/list-proposals))))
            (is (every? #(= 1 (count (:proposal/forks %))) (props/list-proposals)))))))))

(deftest a-member-withdraws-without-tearing-down-the-campaign
  (testing "abandon! inside a campaign discards only this agent's forks"
    (ctx/with-server-context
      (let [sys-conn (fresh-system-db)]
        (with-redefs [sdb/get-conn (fn [] sys-conn)]
          (let [[scope] (fresh-kb)
                kb-conns [{:name "Handbook" :conn (branching/get-kb-conn scope)
                           :db-scope scope}]
                room (random-uuid)
                ada-ctx (agent-sandbox kb-conns room (random-uuid))
                bob-ctx (agent-sandbox kb-conns room (random-uuid))]
            (sci/eval-string* ada-ctx "(proposal/open-campaign! \"Q3 close\")")
            (sci/eval-string* bob-ctx "(proposal/join-campaign!)")
            (sci/eval-string* ada-ctx "(kb/ensure-page! \"Handbook\" \"Ada's section\")")
            (sci/eval-string* bob-ctx "(kb/ensure-page! \"Handbook\" \"Bob's section\")")
            (is (= 1 (:discarded (sci/eval-string* ada-ctx "(proposal/abandon!)"))))
            ;; Bob is still in it, and his branch is untouched
            (let [forks (:forks (sci/eval-string* bob-ctx "(proposal/active)"))]
              (is (= 1 (count forks)))
              (is (page-on-branch? scope (keyword (:branch (first forks))) "Bob's section")))
            (let [filed (stub-summary #(sci/eval-string* bob-ctx "(proposal/file!)"))]
              (is (= 1 (:forks filed))))))))))
